# Generated by Django 4.1.6 on 2023-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=30)),
                ('marks', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=15)),
                ('domain', models.CharField(max_length=30)),
                ('disc', models.TextField()),
                ('experience', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=20)),
                ('serveice1', models.CharField(max_length=20)),
                ('serveice2', models.CharField(max_length=20, null=True)),
                ('serveice3', models.CharField(max_length=20, null=True)),
                ('serveice4', models.CharField(max_length=20, null=True)),
                ('serveice5', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
