# Generated by Django 4.1.6 on 2023-02-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pic1',
            field=models.ImageField(default=None, upload_to='picture_raunak'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pic2',
            field=models.ImageField(default=None, upload_to='picture_raunak'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pic3',
            field=models.ImageField(default=None, upload_to='picture_raunak'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(default=None, upload_to='resume'),
            preserve_default=False,
        ),
    ]
