# Generated by Django 4.1.6 on 2023-02-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_portfolio_pic1_portfolio_pic2_portfolio_pic3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serveice2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='serveice3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='serveice4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='serveice5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
